### ISSUE TITLE
issue13: Finish README.md

### ISSUE THREAD

**Issue by annapoli98** [annapoli98/birthdays#19]
Write instructions in README.md

**Comment by giuliabasaglia** [comment]
First step done at commit  https://github.com/hapoli/birthdays/commit/696c2bb9cfbd12bd38966e1cbbba9a8f103deaee 
Next step:
add verbosity

**Comment by giuliabasaglia** [comment]
https://github.com/hapoli/birthdays/commit/8263a9661eaa24740b297a3681ba8d2d55274eb6
